config/routes.rb
TaskMagic::Application.routes.draw do

  root to: 'tasks#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions
  resources :users do
    resources :tasks
  end
  resources :tasks do
    get 'calendar', :on => :collection
  end
  resources :subtasks
  resources :platforms
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController

  before_filter :require_login
  before_filter :admin_only

  def index
    @platforms = Platform.all
  end

  def show
    @platform = Platform.find(params[:id])
  end

  def new
    @platform = Platform.new
  end

  def edit
    @platform = Platform.find(params[:id])
  end

  def create
    @platform = Platform.new(params[:platform])

    if @platform.save
      redirect_to platforms_url, notice: 'Platform was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @platform = Platform.find(params[:id])

    if @platform.update_attributes(params[:platform])
      redirect_to @platform, notice: 'Platform was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @platform = Platform.find(params[:id])
    @platform.destroy

    redirect_to platforms_url
  end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.erb
<%= form_for(@platform) do |f| %>
  <% if @platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% @platform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<h1>Editing platform</h1>

<%= render 'form' %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/platforms/index.html.erb
<h2>Platform</h2>

<ul>
  <% @platforms.each do |platform| %>
    <li><%= link_to platform.name, platform %></li>
  <% end %>
</ul>

<%= link_to 'New Platform', new_platform_path, class: 'btn' %>

app/views/platforms/new.html.erb
<h1>New platform</h1>

<%= render 'form' %>

<%= link_to 'Back', platforms_path %>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Platform:</b>
  <%= @platform.name %>
</p>

<p>
  <b>Platform Tasks:</b>
  <ul>
    <% @platform.tasks.each do |task| %>
      <li><%= task.title %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_platform_path(@platform) %> |
<%= link_to 'Back', platforms_path %>