config/routes.rb
TaskMagic::Application.routes.draw do

  root to: 'tasks#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions
  resources :users do
    resources :tasks
  end
  resources :tasks do
    get 'calendar', :on => :collection
  end
  resources :subtasks
  resources :platforms
end

app/models/task.rb
class Task < ActiveRecord::Base
	PRIORITY_LEVELS = [['urgent', 1], ['high', 2], ['normal', 3], ['low', 4], ['lowest', 5]]
	STATUS_LEVELS = ['open', 'pending', 'postponed', 'closed']

	belongs_to :user
	belongs_to :platform
	has_many :subtasks

 	attr_accessible :description, :due_date, :priority, :status, :title, :platform_id, :user_id

  validates_presence_of :title, :priority, :status, :user

	def priority_name
		if priority == 5
			'lowest'
		elsif priority == 4
			'low'
		elsif priority == 3
			'normal'	
		elsif priority == 2
			'high'
		elsif priority == 1
			'urgent'
		end
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :require_login
  
  def index
    if params[:user_id]
      @tasks = Task.order('priority asc, due_date desc').where(:user_id => params[:user_id])
    else
      @tasks = Task.order('priority asc, due_date desc').all
    end
    @task = Task.new
  end
  
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    # @task_ordered_after = @task.get_before(@task.priority, @task.due_date)

    if @task.save
      respond_to do |format|
        format.js
        format.html {redirect_to tasks_url}
      end
    else
      render 'new'
    end
  end
  
  def show
    @task = Task.find(params[:id])
    @subtask = Subtask.new
    @subtask.task_id = @task.id
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    
    if @task.update_attributes(params[:task])
      respond_to do |format|
        format.js
        format.html {redirect_to tasks_url}
      end
    else
      render 'show'
    end
  end
  
  def destroy
    @task = Task.destroy(params[:id])

    respond_to do |format|
      format.js
      format.html {redirect_to tasks_url}
    end
  end

  def calendar
    @tasks = Task.all
    @tasks_by_date = @tasks.group_by(&:due_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/tasks/_error.html.erb
<% @task.errors.full_messages.each do |error| %>
  <li class="error_msg">Error: <%= error %></li>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for @task do |t| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="edit_form_label">
    <%= t.label :platform_id %>:
  </div>
  <div class="edit_form_detail">     
    <%= t.collection_select :platform_id, Platform.all, :id, :name, include_blank: true %>
  </div>

  <div class="edit_form_label">
    <%= t.label :title, "Title:" %>
  </div>
  <div class="edit_form_title"> 
    <%= t.text_field :title %>
  </div>

  <div class="edit_form_label" style="clear: both;">
    <%= t.label :priority, "Priority:" %>
  </div>
  <div class="edit_form_detail">
    <%= t.select :priority, Task::PRIORITY_LEVELS %>
  </div>

  <div class="edit_form_label">
    <%= t.label :due_date %>:
  </div>
  <div class="edit_form_detail">    
    <%# t.text_field :due_date, class: "datepicker", :value => @task.due_date.strftime("%m/%d/%Y") %>
    <%= t.text_field :due_date, class: "datepicker" %>
    <%= t.hidden_field :due_date, class: "datepicker_db_format" %>
  </div>

  <div class="edit_form_label">
    <%= t.label :status %>:
  </div>
  <div class="edit_form_detail">    
    <%= t.select :status, Task::STATUS_LEVELS %>
  </div>

  <div class="edit_form_label">
    <%= t.label :user_id %>:
  </div>
  <div class="edit_form_detail">     
    <%= t.collection_select :user_id, User.all, :id, :name, include_blank: true %>
  </div>

  <div class="edit_form_label">
    <%= t.label :description %>:
  </div>
  <div class="edit_form_description">
    <%= t.text_area :description %>
  </div>

    <div class="edit_form_action">
      <%= t.submit %>
    </div>
<% end %>

<%= button_to "Cancel", tasks_url, :method => "get" %>

app/views/tasks/_form_ajax.html.erb
<%= form_for task, remote: true do |t| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3><%= t.text_field :title, required: 'required', placeholder: "Title" %></h3>

  <%= t.collection_select :user_id, User.all, :id, :name, prompt: "Assignee" %>
  
  <%= t.collection_select :platform_id, Platform.all, :id, :name, prompt: "Platform", include_blank: true %>

  <%= t.select :priority, Task::PRIORITY_LEVELS %>

  <%= t.select :status, Task::STATUS_LEVELS, prompt: "Status" %>

  <%= t.text_field :due_date, class: "datepicker", :value => task.due_date.try(:strftime, "%m/%d/%Y") %>
  <%#= t.text_field :due_date, class: "datepicker", placeholder: "Due Date" %>
  <%= t.hidden_field :due_date, class: "datepicker_db_format" %>


  
  <%= t.text_area :description, placeholder: "Task Description" %>

  <%= t.submit %>
  <%= link_to "Cancel", "#", class: "cancel_form_link" %>
<% end %>

app/views/tasks/_subtask_form.html.erb
<%= form_for(@subtask) do |f| %>

  <%= f.hidden_field :task_id %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :platform_id %><br />
    <%= f.collection_select :platform_id, Platform.all, :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.text_field :due_date, class: "datepicker" %>
    <%= f.hidden_field :due_date, class: "datepicker_db_format" %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select :priority, Task::PRIORITY_LEVELS %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Task::STATUS_LEVELS %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/tasks/_subtasks_list.html.erb
<h2>Subtasks</h2>

<% if @task.subtasks.present? %>
  <%= render "tasks/tasks_list", items: @task.subtasks %>
<% end %>

<%= link_to "Add Subtask", new_subtask_url(:task_id => @task.id) %>

app/views/tasks/_task_show.html.erb
<h3>
  <% if item.class == Subtask %>
    #<%= item.task_id %>-<%= item.id %>: <%=  item.title %>
  <% else %>
    #<%= item.id %>: <%= item.title %>
  <% end %>
</h3>

<div id="content">

  Platform: <%= item.platform.try(:name) %>

  Priority: <%= item.priority_name.capitalize %>

  Assignee: <%= item.user.name %>

  Status: <%= item.status.capitalize %>

  Due Date:
    <% if item.due_date.present? %>
      <%= item.due_date.strftime("%A, %B %-d, %Y") %>
    <% end %>

  Description: <%= item.description %>

  <%= link_to "Edit Task", "#", class: "btn edit_link", id: "#{item.id}" %>
  <%= link_to "Cancel", "#", class: "cancel_show_link" %>

  <% if admin_user %>
    <%= link_to "Delete Task", item, method: :delete, remote: true, class: "btn" %>
  <% end %>
  

  <p class="timestamp">
    <% if item.created_at != item.updated_at %>
      Updated at: <%= item.updated_at.strftime("%A, %B %-d, %Y @ %I:%M%p") %>
    <% else %>
      Created at: <%= item.created_at.strftime("%A, %B %-d, %Y @ %I:%M%p") %> 
    <% end %>
  </p>

  <%= render 'form_ajax', task: item %>

</div>

app/views/tasks/_tasks_list.html.erb
<tr id="item_<%= item.id %>">
    <%#= form_tag item, :method => "put" do %>
      <%#= select_tag :status, options_for_select(Task::STATUS_LEVELS, item.status), :name => "#{class_name(item)}[status]", :onchange => "this.form.submit();" %>
    <%# end %>
  <td class="priority">
    <span class="badge badge-<%= item.priority %>"><%= item.priority %></span>
  </td>
  <td class="title">
    <%= link_to "##{item.id} - #{item.platform.try(:name)}: #{item.title}", "#", class: "task_title", id: "#{item.id}" %>        
  </td>
  <td class="assignee">
    <%= item.user.name %>
  </td>
  <td class="due_date">
    <%= item.due_date.try(:strftime, "%-m/%-d/%y") %>
  </td>
</tr>
<% if item.class == Task %>
  <% if item.subtasks.present? %>
    <% item.subtasks.each do |subitem| %>
      <tr>
        <td></td>
        <td class="title">
          <span class="badge badge-<%= item.priority %>"><%= item.priority %></span>
          <%= link_to " ##{subitem.task_id}-#{subitem.id} - #{subitem.platform.try(:name)}: #{subitem.title}", subitem, id: "#{subitem.id}" %>
        </td>
        <td class="assignee"><%= subitem.user.name %></td>
        <td class="due_date">
          <%= subitem.due_date.try(:strftime, "%-m/%-d/%y") %>
        </td>
      </tr>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/calendar.html.erb
<h2 id="month">
  <%= link_to "<", date: @date.prev_month %>
  <%= @date.strftime("%B %Y") %>
  <%= link_to ">", date: @date.next_month %>
</h2>

<%= calendar @date do |date| %>
  <%= date.day %>
  <% if @tasks_by_date[date] %>
  <ul>
    <% @tasks_by_date[date].each do |task| %>
      <li><%= link_to task.title, task %></li>
    <% end %>
  </ul>
  <% end %>
<% end %>

app/views/tasks/destroy.js.erb
$(".task_details").hide( "slide", {direction: "right"}, 800 );
$('#item_<%= @task.id %>').hide();

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render "form" %>

app/views/tasks/index.html.erb
<%= link_to "New Task", new_task_url, id: "new_link", remote: true %>

<div class="new_task_container ui-widget-content ui-corner-all">
  <%= render "form_ajax", task: @task %>
</div>

<% @tasks.each do |task| %>
  <div class="task_details <%= task.id %> ui-widget-content ui-corner-all">
    <%= render "task_show", item: task %>
  </div>
<% end %>

<% Task::STATUS_LEVELS.each do |status| %>
  <h2><%= status.capitalize %></h2>
  <table class="table" id="<%= status %>">
    <tbody>
      <% @tasks.each do |task| %>
        <% if task.status == status %>
          <%= render "tasks_list", item: task %>
        <% end %>
      <% end %>
    </tbody>
  </table>  
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render "form" %>

<%= link_to "Cancel", tasks_url %>

app/views/tasks/show.html.erb
<span id="notice"><%= notice %></span>

<div id="task">
	<%= render "task_show", :item => @task %>
</div>

<div id="subtask">
  <%= render "subtasks_list" %>
</div>

<%= link_to "Return to Tasks", tasks_url %>

app/views/tasks/update.js.erb
$(".edit_task").hide();
$(".task_details.<%= @task.id %>").replaceWith("<div class='task_details <%= @task.id %> ui-widget-content ui-corner-all'><%= j render('task_show', item: @task) %></div>");
$(".task_details.<%= @task.id %>").show();
$("#item_<%= @task.id %>").replaceWith("<%= j render('tasks_list', item: @task) %>");