config/routes.rb
TaskMagic::Application.routes.draw do

  root to: 'tasks#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions
  resources :users do
    resources :tasks
  end
  resources :tasks do
    get 'calendar', :on => :collection
  end
  resources :subtasks
  resources :platforms
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  belongs_to :platform
  belongs_to :user

  attr_accessible :description, :due_date, :priority, :status, :task_id, :title, :platform_id, :user_id

  validates_presence_of :title, :task, :priority, :status, :platform, :user

  # subtask should not be due after tasks's due date
  # subtask should not have a priority lower than it's task's priority

  # update subtask priority level if task priority level is raised

  # validate :priority_level

  # def priority_level
  #   if self.priority < self.task.priority
  #     self.errors.add(:priority, "must equal or be higher than it's parent's priority level (#{self.task.priority_name.capitalize}).")
  #   end
  # end

  def priority_name
    if priority == 1
      "lowest"
    elsif priority == 2
      "low"
    elsif priority == 3
      "normal"  
    elsif priority == 4
      "high"
    elsif priority == 5
      "urgent"
    end
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController

  before_filter :require_login
  before_filter :admin_only, :only => [:index, :destoy]

  def index
    @subtasks = Subtask.all
  end

  def new
    @subtask = Subtask.new
    @task_id = params[:task_id]
  end

  def create
    @subtask = Subtask.new(params[:subtask])
    
    if @subtask.save
      redirect_to task_url(@subtask.task_id), notice: 'Subtask was successfully created.'
    else
      render action: "new"
    end
  end

  def show
    @subtask = Subtask.find(params[:id])
  end

  def edit
    @subtask = Subtask.find(params[:id])
  end

  def update
    @subtask = Subtask.find(params[:id])

    if @subtask.update_attributes(params[:subtask])
      redirect_to @subtask, notice: 'Subtask was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @subtask = Subtask.find(params[:id])
    @subtask.destroy

    redirect_to task_url(@subtask.task_id)
  end
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/views/subtasks/_form.html.erb
<%= form_for(@subtask) do |f| %>
  <% if @subtask.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @subtask.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :task_id, value: @task_id %>

  <div class="edit_form_label">
    <%= f.label :platform_id %>:
  </div>
  <div class="edit_form_detail">     
    <%= f.collection_select :platform_id, Platform.all, :id, :name, :include_blank => true %>
  </div>

  <div class="edit_form_label">
    <%= f.label :title, "Title:" %>
  </div>
  <div class="edit_form_title">    
    <%= f.text_field :title %>
  </div>
  
  <div class="edit_form_label" style="clear: both;">
    <%= f.label :priority, "Priority:" %>
  </div>
  <div class="edit_form_detail">
    <%= f.select :priority, Task::PRIORITY_LEVELS %>
  </div>

  <div class="edit_form_label">
    <%= f.label :status %>:
  </div>
  <div class="edit_form_detail">    
    <%= f.select :status, Task::STATUS_LEVELS %>
  </div>
  
  <div class="edit_form_label">
    <%= f.label :user_id %>:
  </div>
  <div class="edit_form_detail">     
    <%= f.collection_select :user_id, User.all, :id, :name, value: current_user %>
  </div>

  <div class="edit_form_label">
    <%= f.label :due_date %>:
  </div>
  <div class="edit_form_detail"> 
    <%= f.text_field :due_date, class: 'datepicker' %>
    <%= f.hidden_field :due_date, class: 'datepicker_db_format' %>
  </div>

  <div class="edit_form_label" style="clear: both;">
    <%= f.label :description %>:
  </div>
  <div class="edit_form_description">     
    <%= f.text_area :description %>
  </div>

  <div class="edit_form_action">
    <%= f.submit %>
  </div>
<% end %>

<%# button_to 'Cancel', task_path(@subtask.task_id), :method => 'get' %>

app/views/subtasks/edit.html.erb
<h1>Editing subtask</h1>

<%= render 'form' %>

app/views/subtasks/new.html.erb
<h1>New subtask</h1>

<%= render 'form' %>

<%= link_to 'Back', subtasks_path %>

app/views/subtasks/show.html.erb
<p id="notice"><%= notice %></p>

<div id="subtask">
  <%= render 'tasks/task_show', :item => @subtask %>
</div>

<%= link_to "Return to Task", task_url(@subtask.task_id) %>