config/routes.rb
TaskMagic::Application.routes.draw do

  root to: 'tasks#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions
  resources :users do
    resources :tasks
  end
  resources :tasks do
    get 'calendar', :on => :collection
  end
  resources :subtasks
  resources :platforms
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TaskMagic</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="<%= tasks_url %>">TaskMagic <i class='icon-magic'></i></a>
      <ul class="nav">
      <% if admin_user %>
        <li><%= link_to raw("<i class='icon-desktop'></i> Platforms"), platforms_url %></li>
        <li><%= link_to raw("<i class='icon-user'></i> Users"), users_url %></li>
      <% end %>
      <% if current_user %>
        <li><%= link_to raw("<i class='icon-reorder'></i> Tasks"), tasks_url %></li>
        <li><%= link_to raw("<i class='icon-calendar'></i> Calendar"), calendar_tasks_url %></li>
      </ul>
      <ul class="nav pull-right">
        <li>
          <a href="users/<%= current_user.id %>/edit">
            <span class="icon-user"></span>
            <%= current_user.name %>
          </a>
        </li>
        <li style="padding-top: 10px;">|</li>
        <li><%= link_to raw("<i class='icon-signin'></i> Logout"), logout_url %></li>
      </ul>
      <% end %>
    </div>
  </div>

  <div class="container">
    <%= notice %>
    <%= yield %>
  </div>

</body>
</html>